Add CI test with spdk
Signed-off-by: Boris Glimcher <Boris.Glimcher@emc.com>

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -57,3 +57,31 @@ jobs:
           labels: ${{ steps.meta.outputs.labels }}
           cache-from: type=gha
           cache-to: type=gha,mode=max
+
+  test-with-spdk:
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v3
+    - uses: docker/setup-qemu-action@v2
+    - uses: docker/setup-buildx-action@v2.4.1
+    - name: Start containers
+      run: docker-compose up --build --force-recreate --detach
+    - name: Run Tests
+      run: |
+        set -x
+        docker-compose ps
+        name=$(docker-compose ps | grep client | awk '{print $1}')
+        rc=$(docker wait "${name}")
+        if [ "${rc}" != "0" ]; then
+            echo "client failed:"
+            docker logs "${name}"
+            exit 1
+        fi
+
+    - name: Logs
+      if: always()
+      run: docker-compose logs
+
+    - name: Stop containers
+      if: always()
+      run: docker-compose down
