ci: copy docker action from actions repo
Signed-off-by: Artsiom Koltun <artsiom.koltun@intel.com>

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -13,10 +13,100 @@ permissions:
   contents: read
 
 jobs:
-  call:
+  build:
+
+    runs-on: ubuntu-latest
     permissions:
       contents: read
       packages: write
+      # This is used to complete the identity challenge
+      # with sigstore/fulcio when running outside of PRs.
       id-token: write
-    uses: opiproject/actions/.github/workflows/docker-publish.yml@main
-    secrets: inherit
+
+    steps:
+      - uses: actions/checkout@v4
+      - uses: docker/setup-qemu-action@v3
+      - uses: docker/setup-buildx-action@v3.0.0
+
+      - name: Log in to Docker Hub
+        if: github.event_name != 'pull_request'
+        uses: docker/login-action@v3.0.0
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+      - name: Log in to the GH Container registry
+        if: github.event_name != 'pull_request'
+        uses: docker/login-action@v3.0.0
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Extract Docker metadata
+        id: meta
+        uses: docker/metadata-action@v5.0.0
+        with:
+          images: |
+            ${{ github.repository }}
+            ghcr.io/${{ github.repository }}
+      - name: Get opi-api Version Info
+        run: echo "OPI_API_VERSION=$(go list -m -f '{{.Version}}' github.com/opiproject/opi-api || echo 'undefined')" >> $GITHUB_ENV
+
+      - name: Build and push Docker image
+        id: build-and-push
+        uses: docker/build-push-action@v5.0.0
+        with:
+          context: .
+          platforms: linux/amd64,linux/arm64
+          push: ${{ github.event_name != 'pull_request' }}
+          tags: ${{ steps.meta.outputs.tags }}
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
+          labels: |
+            ${{ steps.meta.outputs.labels }},
+            opi-api-version=${{ env.OPI_API_VERSION }}
+
+      - name: Update Docker Hub Description
+        if: github.event_name != 'pull_request'
+        uses: peter-evans/dockerhub-description@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN_DELETE }}
+          repository: ${{ github.repository }}
+          short-description: ${{ github.event.repository.description }}
+
+  test:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: docker/setup-qemu-action@v3
+      - uses: docker/setup-buildx-action@v3.0.0
+
+      - name: Install additional kernel modules needed for OPI like VRF
+        run: sudo apt-get install linux-modules-extra-$(uname -r)
+
+      - name: Load additional kernel modules needed for OPI like VRF
+        run: sudo modprobe -v vrf
+
+      - name: Start containers
+        run: docker-compose up --build --force-recreate --detach opi-test
+
+      - name: Run Tests
+        run: |
+          set -x
+          name=$(docker-compose ps | grep opi-test | awk '{print $1}')
+          rc=$(docker wait "${name}")
+          if [ "${rc}" != "0" ]; then
+              echo "opi-test failed:"
+              docker logs "${name}"
+              exit 1
+          fi
+
+      - name: Logs
+        if: always()
+        run: docker-compose logs
+
+      - name: Stop containers
+        if: always()
+        run: docker-compose down --volumes --remove-orphans
